[licenses]
allow = [
  # permissive licenses
  "Apache-2.0",
  "BSL-1.0",
  "MIT",
  "Unlicense",
  "Unicode-3.0",
  "Zlib",
  # permissive license with unclear patent grant
  "CC0-1.0",
]

[advisories]
ignore = [
  # https://rustsec.org/advisories/RUSTSEC-2024-0436 paste! is unmaintained
  "RUSTSEC-2024-0436",
]
yanked = "warn"

[bans]
multiple-versions = "allow"
